export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER";

export const PROFILE_VIEW_PAGE = "PROFILE_VIEW_PAGE";
export const PROFILE_EDIT_PAGE = "PROFILE_EDIT_PAGE";
export const REGISTER_CONTROL = "REGISTER_CONTROL";
export const PASSWORD_CHANGE = "PASSWORD_CHANGE";
export const GET_EMAIL = "GET_EMAIL";
export const LOST_PASSWORD_CONTROL = "LOST_PASSWORD_CONTROL";
export const PASSWORD_RESET = "PASSWORD_RESET";

export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_ADD = "PRODUCT_ADD";
export const PRODUCT_REMOVE = "PRODUCT_REMOVE";
export const PRODUCT_EDIT = "PRODUCT_EDIT";
export const PRODUCT_COUNT = "PRODUCT_COUNT"

export const STOCK_VIEW_PAGE = "STOCK_VIEW_PAGE";
export const ADD_DEVICE = "ADD_DEVICE";
export const STOCK_REMOVE = "STOCK_REMOVE";
export const STOCK_EDIT = "STOCK_EDIT"

export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const SHOPPING_CART = "SHOPPING_CART";
export const MY_ORDERS = "MY_ORDERS";

export const NOTIFICATION_TO_COMMUNITY = "NOTIFICATION_TO_COMMUNITY";
export const NOTIFICATION_TO_PERSON = "NOTIFICATION_TO_PERSON";
export const NOTIFICATION_TO_EVERYONE = "NOTIFICATION_TO_EVERYONE";
export const NOTIFICATION_ID_LIST = "NOTIFICATION_ID_LIST";
export const NOTIFICATION_VIEW_PAGE = "NOTIFICATION_VIEW_PAGE";

export const COUNTRY = "COUNTRY";
export const CONTACT_FORM = "CONTACT_FORM";



//action types belirlendi
