export default {
  login: "",
  register: "",
  profile: "",
  product: "",
  stock: "",
  productadd: "",
  profileedit: "",
  cart:[],
  shopping:"",
  password:"",
  device:"",
  token:"",
  stockRemove:"",
  productRemove:"",
  notificaton1:"",
  notificaton2:"",
  notificaton3:"",
  notificatonIdList:"",
  productEdit:"",
  stockEdit:"",
  country:["a","b"],
  productCount:"",
  email:"",
  contact:"",
  notification:[],
  lostpassword:"",
};
//default parametreler oluşturuldu
